services:
  build:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/my-project
    working_dir: /my-project/ns-3
    command: bash -c "./waf configure -d optimized && ./waf clean  && ./waf build"
    environment:
      - CXXFLAGS=-Wall -frounding-math

  dirty-build:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/my-project
    working_dir: /my-project/ns-3
    command: bash -c "./waf configure -d optimized && ./waf build"
    environment:
      - CXXFLAGS=-Wall -frounding-math

  shell:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/my-project
    working_dir: /my-project/ns-3
    command: bash
    tty: true
    stdin_open: true
    environment:
      - CXXFLAGS=-Wall -frounding-math

  simulation:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/my-project
    working_dir: /my-project/ns-3
    command: bash -c 'NS_LOG="*=error" NS_GLOBAL_VALUE="RngRun=1" ./waf --run "${SIMULATION_CMD}"'
    environment:
      - CXXFLAGS=-Wall -frounding-math
      #- SIMULATION_CMD=first
