x-common: &common
  image: my-ns3-project:latest
  volumes:
    - ./:/my-project
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
  working_dir: /my-project/ns-3
  environment:
    #- CXXFLAGS=-Wall
    - CXXFLAGS=-Wall -O3 -frounding-math
    # the variable below goes into the .env file
    #- CONFIGURE_OPTIONS=-d optimized
# entrypoint: ["/my-project/libs/setup-libs.sh"]

services:
  build:
    <<: *common
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: bash -c "./waf configure ${CONFIGURE_OPTIONS} && ./waf clean && ./waf build"

  dirty-build:
    <<: *common
    command: bash -c "./waf configure ${CONFIGURE_OPTIONS} && ./waf build"

  shell:
    <<: *common
    command: bash -c "bash"
    tty: true
    stdin_open: true

  simulation:
    <<: *common
    command: bash -c './waf --run "${SIMULATION_CMD}"'
    environment:
      - NS_LOG=*=error
      #- NS_GLOBAL_VALUE=RngRun=1
