x-common: &common
  build:
    context: .
    dockerfile: docker/Dockerfile
  volumes:
    - ./:/my-project
  working_dir: /my-project/ns-3
  environment:
    - CXXFLAGS=-Wall -O3 # -03 is for max optimization. Simulations run 75% faster
  # - CXXFLAGS=-Wall -frounding-math -O3
services:
  build:
    <<: *common
    command: bash -c "./waf configure -d optimized && ./waf clean && ./waf build"

  dirty-build:
    <<: *common
    command: bash -c "./waf configure -d optimized && ./waf build"

  shell:
    <<: *common
    command: bash
    tty: true
    stdin_open: true

  simulation:
    <<: *common
    command: bash -c './waf --run "${SIMULATION_CMD}"'
    environment:
      - NS_LOG=*=error
      - NS_GLOBAL_VALUE=RngRun=1
