#!/bin/bash

n=$1
shift
cmd="$@"

# Get the directory of the current script
script_dir=$(dirname "$0")

for i in $(seq 1 $n); do
  # Use the correct relative path to runwithtimer.sh
  "$script_dir/runwithtimer.sh" $cmd
  echo -e "\n\n ---------------------------------------"
done
